

SELECT c.FIRSTNAME,c.LASTNAME FROM CUSTOMER c inner join ORDERS o on c.CUSTOMER_ID=o.CUSTOMER_ID WHERE TOTAL_PRICE>500

SELECT c.FIRSTNAME,c.LASTNAME from CUSTOMER c inner join ORDERS o on c.CUSTOMER_ID=o.CUSTOMER_ID  WHERE ORDER_DATE= convert(date,getdate())

SELECT c.FIRSTNAME,c.LASTNAME from CUSTOMER c  inner join ORDERS o on c.CUSTOMER_ID=o.CUSTOMER_ID  WHERE ORDER_ID=2002 AND TOTAL_PRICE BETWEEN 
 2000 AND 5000       



